-- This file is auto-generated by import_quran_data.go
-- Run: cd database/scripts && go run import_quran_data.go

-- Initial roles
INSERT INTO roles (id, name, description) VALUES
(1, 'admin', 'System administrator with full access'),
(2, 'teacher', 'Teacher who can input memorization records'),
(3, 'parent', 'Parent who can view their children''s progress');

-- Initial permissions
INSERT INTO permissions (name, resource, action) VALUES
('create_memorization', 'memorization', 'create'),
('view_children_progress', 'student', 'read'),
('manage_users', 'user', 'manage'),
('view_assigned_students', 'student', 'read'),
('access_all_data', 'all', 'all');

-- Role permissions
INSERT INTO role_permissions (role_id, permission_id) VALUES
-- Teacher permissions
(2, 1), -- create_memorization
(2, 4), -- view_assigned_students
-- Parent permissions
(3, 2), -- view_children_progress
-- Admin permissions (all)
(1, 1), (1, 2), (1, 3), (1, 4), (1, 5);
